name: 'Extract Version from Cargo.toml'
description: 'Extracts the version from Cargo.toml using improved pattern matching'

outputs:
  cargo_version:
    description: 'The version extracted from Cargo.toml'
    value: ${{ steps.extract.outputs.cargo_version }}

runs:
  using: 'composite'
  steps:
    - name: Extract version from Cargo.toml
      id: extract
      shell: bash
      run: |
        CARGO_VERSION=$(grep '^version\s*=\s*"' Cargo.toml | sed 's/.*"\([^"]*\)".*/\1/')
        echo "cargo_version=$CARGO_VERSION" >> $GITHUB_OUTPUT
        echo "Cargo.toml version: $CARGO_VERSION"