apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-secrets-operator
  namespace: openfga-system
  labels:
    app.kubernetes.io/name: vault-secrets-operator
    app.kubernetes.io/component: controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vault-secrets-operator
  labels:
    app.kubernetes.io/name: vault-secrets-operator
    app.kubernetes.io/component: controller
rules:
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["secrets.hashicorp.com"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vault-secrets-operator
  labels:
    app.kubernetes.io/name: vault-secrets-operator
    app.kubernetes.io/component: controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vault-secrets-operator
subjects:
- kind: ServiceAccount
  name: vault-secrets-operator
  namespace: openfga-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vault-secrets-operator-leader-election
  namespace: openfga-system
  labels:
    app.kubernetes.io/name: vault-secrets-operator
    app.kubernetes.io/component: controller
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vault-secrets-operator-leader-election
  namespace: openfga-system
  labels:
    app.kubernetes.io/name: vault-secrets-operator
    app.kubernetes.io/component: controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vault-secrets-operator-leader-election
subjects:
- kind: ServiceAccount
  name: vault-secrets-operator
  namespace: openfga-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-secrets-operator
  namespace: openfga-system
  labels:
    app.kubernetes.io/name: vault-secrets-operator
    app.kubernetes.io/component: controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: vault-secrets-operator
      app.kubernetes.io/component: controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vault-secrets-operator
        app.kubernetes.io/component: controller
    spec:
      serviceAccountName: vault-secrets-operator
      containers:
      - name: manager
        image: hashicorp/vault-secrets-operator:0.4.3
        imagePullPolicy: IfNotPresent
        args:
        - --leader-elect
        - --zap-log-level=info
        ports:
        - containerPort: 8080
          name: metrics
          protocol: TCP
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        env:
        - name: OPERATOR_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 65532
        volumeMounts:
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: tmp
        emptyDir: {}
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: vault-secrets-operator-webhook-service
  namespace: openfga-system
  labels:
    app.kubernetes.io/name: vault-secrets-operator
    app.kubernetes.io/component: webhook
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    app.kubernetes.io/name: vault-secrets-operator
    app.kubernetes.io/component: controller