apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
  namespace: openfga-system
  labels:
    app.kubernetes.io/name: vault
    app.kubernetes.io/component: server
data:
  vault.hcl: |
    ui = true
    
    listener "tcp" {
      tls_disable = 1
      address = "[::]:8200"
      cluster_address = "[::]:8201"
    }
    
    storage "file" {
      path = "/vault/data"
    }
    
    # Auto-unseal for development
    seal "auto" {
      type = "dev"
    }
    
    # Development mode configuration
    api_addr = "http://0.0.0.0:8200"
    cluster_addr = "http://0.0.0.0:8201"
    
    # Enable KV secrets engine
    default_lease_ttl = "168h"
    max_lease_ttl = "720h"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault
  namespace: openfga-system
  labels:
    app.kubernetes.io/name: vault
    app.kubernetes.io/component: server
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vault-auth
  labels:
    app.kubernetes.io/name: vault
    app.kubernetes.io/component: server
rules:
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["serviceaccounts/token"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vault-auth
  labels:
    app.kubernetes.io/name: vault
    app.kubernetes.io/component: server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vault-auth
subjects:
- kind: ServiceAccount
  name: vault
  namespace: openfga-system
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-storage
  namespace: openfga-system
  labels:
    app.kubernetes.io/name: vault
    app.kubernetes.io/component: server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  namespace: openfga-system
  labels:
    app.kubernetes.io/name: vault
    app.kubernetes.io/component: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: vault
      app.kubernetes.io/component: server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vault
        app.kubernetes.io/component: server
    spec:
      serviceAccountName: vault
      containers:
      - name: vault
        image: hashicorp/vault:1.15.2
        imagePullPolicy: IfNotPresent
        command:
        - vault
        - server
        - -config=/vault/config/vault.hcl
        - -dev
        - -dev-root-token-id=root
        - -dev-listen-address=0.0.0.0:8200
        ports:
        - containerPort: 8200
          name: http
          protocol: TCP
        - containerPort: 8201
          name: cluster
          protocol: TCP
        env:
        - name: VAULT_ADDR
          value: "http://127.0.0.1:8200"
        - name: VAULT_API_ADDR
          value: "http://0.0.0.0:8200"
        - name: VAULT_CLUSTER_ADDR
          value: "http://0.0.0.0:8201"
        - name: VAULT_DEV_ROOT_TOKEN_ID
          value: "root"
        - name: VAULT_LOG_LEVEL
          value: "info"
        volumeMounts:
        - name: vault-config
          mountPath: /vault/config
          readOnly: true
        - name: vault-storage
          mountPath: /vault/data
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /v1/sys/health?standbyok=true
            port: 8200
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /v1/sys/health?standbyok=true&uninitcode=204&sealedcode=204
            port: 8200
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 5
      volumes:
      - name: vault-config
        configMap:
          name: vault-config
      - name: vault-storage
        persistentVolumeClaim:
          claimName: vault-storage
---
apiVersion: v1
kind: Service
metadata:
  name: vault
  namespace: openfga-system
  labels:
    app.kubernetes.io/name: vault
    app.kubernetes.io/component: server
spec:
  type: ClusterIP
  ports:
  - port: 8200
    targetPort: 8200
    protocol: TCP
    name: http
  - port: 8201
    targetPort: 8201
    protocol: TCP
    name: cluster
  selector:
    app.kubernetes.io/name: vault
    app.kubernetes.io/component: server
---
apiVersion: v1
kind: Service
metadata:
  name: vault-ui
  namespace: openfga-system
  labels:
    app.kubernetes.io/name: vault
    app.kubernetes.io/component: ui
spec:
  type: NodePort
  ports:
  - port: 8200
    targetPort: 8200
    protocol: TCP
    name: http
    nodePort: 30200
  selector:
    app.kubernetes.io/name: vault
    app.kubernetes.io/component: server