/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenTelemetryConfig) DeepCopyInto(out *OpenTelemetryConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.SamplingRate != nil {
		in, out := &in.SamplingRate, &out.SamplingRate
		*out = new(float64)
		**out = **in
	}
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenTelemetryConfig.
func (in *OpenTelemetryConfig) DeepCopy() *OpenTelemetryConfig {
	if in == nil {
		return nil
	}
	out := new(OpenTelemetryConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenFGAServer) DeepCopyInto(out *OpenFGAServer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenFGAServer.
func (in *OpenFGAServer) DeepCopy() *OpenFGAServer {
	if in == nil {
		return nil
	}
	out := new(OpenFGAServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenFGAServer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenFGAServerList) DeepCopyInto(out *OpenFGAServerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OpenFGAServer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenFGAServerList.
func (in *OpenFGAServerList) DeepCopy() *OpenFGAServerList {
	if in == nil {
		return nil
	}
	out := new(OpenFGAServerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenFGAServerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenFGAServerSpec) DeepCopyInto(out *OpenFGAServerSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	// Add other fields as needed - this is a minimal implementation
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenFGAServerSpec.
func (in *OpenFGAServerSpec) DeepCopy() *OpenFGAServerSpec {
	if in == nil {
		return nil
	}
	out := new(OpenFGAServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenFGAServerStatus) DeepCopyInto(out *OpenFGAServerStatus) {
	*out = *in
	// Add fields as needed
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenFGAServerStatus.
func (in *OpenFGAServerStatus) DeepCopy() *OpenFGAServerStatus {
	if in == nil {
		return nil
	}
	out := new(OpenFGAServerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenFGAStore) DeepCopyInto(out *OpenFGAStore) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenFGAStore.
func (in *OpenFGAStore) DeepCopy() *OpenFGAStore {
	if in == nil {
		return nil
	}
	out := new(OpenFGAStore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenFGAStore) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenFGAStoreList) DeepCopyInto(out *OpenFGAStoreList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OpenFGAStore, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenFGAStoreList.
func (in *OpenFGAStoreList) DeepCopy() *OpenFGAStoreList {
	if in == nil {
		return nil
	}
	out := new(OpenFGAStoreList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenFGAStoreList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenFGAStoreSpec) DeepCopyInto(out *OpenFGAStoreSpec) {
	*out = *in
	// Minimal implementation
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenFGAStoreSpec.
func (in *OpenFGAStoreSpec) DeepCopy() *OpenFGAStoreSpec {
	if in == nil {
		return nil
	}
	out := new(OpenFGAStoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenFGAStoreStatus) DeepCopyInto(out *OpenFGAStoreStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenFGAStoreStatus.
func (in *OpenFGAStoreStatus) DeepCopy() *OpenFGAStoreStatus {
	if in == nil {
		return nil
	}
	out := new(OpenFGAStoreStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthorizationModel) DeepCopyInto(out *AuthorizationModel) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthorizationModel.
func (in *AuthorizationModel) DeepCopy() *AuthorizationModel {
	if in == nil {
		return nil
	}
	out := new(AuthorizationModel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AuthorizationModel) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthorizationModelList) DeepCopyInto(out *AuthorizationModelList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AuthorizationModel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthorizationModelList.
func (in *AuthorizationModelList) DeepCopy() *AuthorizationModelList {
	if in == nil {
		return nil
	}
	out := new(AuthorizationModelList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AuthorizationModelList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthorizationModelSpec) DeepCopyInto(out *AuthorizationModelSpec) {
	*out = *in
	// Minimal implementation
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthorizationModelSpec.
func (in *AuthorizationModelSpec) DeepCopy() *AuthorizationModelSpec {
	if in == nil {
		return nil
	}
	out := new(AuthorizationModelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthorizationModelStatus) DeepCopyInto(out *AuthorizationModelStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthorizationModelStatus.
func (in *AuthorizationModelStatus) DeepCopy() *AuthorizationModelStatus {
	if in == nil {
		return nil
	}
	out := new(AuthorizationModelStatus)
	in.DeepCopyInto(out)
	return out
}