name: CI

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test, Format, and Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [stable]
        include:
          - rust: stable
            check_fmt: true
            check_clippy: true
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust ${{ matrix.rust }}
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.rust }}
        components: ${{ matrix.check_fmt && 'rustfmt' || '' }}${{ matrix.check_clippy && matrix.check_fmt && ',' || '' }}${{ matrix.check_clippy && 'clippy' || '' }}
    
    - name: Install sccache
      uses: mozilla-actions/sccache-action@v0.0.5
      continue-on-error: true
      id: sccache-install
    
    - name: Cache cargo registry and dependencies
      uses: actions/cache@v4
      continue-on-error: true
      with:
        path: |
          ~/.cargo/registry/index
          ~/.cargo/registry/cache
          ~/.cargo/git/db
          target
        key: ${{ runner.os }}-${{ matrix.rust }}-cargo-test-${{ hashFiles('**/Cargo.lock') }}-${{ hashFiles('**/Cargo.toml') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.rust }}-cargo-test-${{ hashFiles('**/Cargo.lock') }}-
          ${{ runner.os }}-${{ matrix.rust }}-cargo-test-
          ${{ runner.os }}-${{ matrix.rust }}-cargo-
          ${{ runner.os }}-cargo-
    
    - name: Configure sccache
      run: |
        # Only configure sccache if it's available and can connect to cache service
        if [ "${{ steps.sccache-install.outcome }}" = "success" ] && command -v sccache >/dev/null 2>&1; then
          echo "✅ sccache installed, testing connectivity to GitHub Actions cache..."
          
          # Test if sccache can start without failing - use a controlled environment
          if SCCACHE_GHA_ENABLED=true timeout 10s sccache --version >/dev/null 2>&1; then
            echo "✅ sccache connectivity verified, enabling for builds"
            echo "SCCACHE_GHA_ENABLED=true" >> $GITHUB_ENV
            echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV
          else
            echo "⚠️ sccache connectivity failed (GitHub cache service may be down)"
            echo "   Continuing build without sccache to ensure reliability"
            echo "   Build will complete successfully but without sccache optimizations"
            # Explicitly do NOT set RUSTC_WRAPPER so builds use rustc directly
            echo "SCCACHE_DISABLED=true" >> $GITHUB_ENV
          fi
        else
          echo "⚠️ sccache not available, proceeding without sccache"
          echo "SCCACHE_DISABLED=true" >> $GITHUB_ENV
        fi
    
    - name: Check formatting
      if: matrix.check_fmt
      run: cargo fmt -- --check
    
    - name: Run clippy
      if: matrix.check_clippy
      run: make clippy
    
    - name: Run compile check
      run: make compile
    
    - name: Run tests
      run: make test

  build:
    name: Build Verification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
    
    - name: Install sccache
      uses: mozilla-actions/sccache-action@v0.0.5
      continue-on-error: true
      id: sccache-install
    
    - name: Cache cargo registry and dependencies
      uses: actions/cache@v4
      continue-on-error: true
      with:
        path: |
          ~/.cargo/registry/index
          ~/.cargo/registry/cache
          ~/.cargo/git/db
          target
        key: ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}-${{ hashFiles('**/Cargo.toml') }}
        restore-keys: |
          ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}-
          ${{ runner.os }}-cargo-build-
          ${{ runner.os }}-cargo-
    
    - name: Configure sccache
      run: |
        # Only configure sccache if it's available and can connect to cache service
        if [ "${{ steps.sccache-install.outcome }}" = "success" ] && command -v sccache >/dev/null 2>&1; then
          echo "✅ sccache installed, testing connectivity to GitHub Actions cache..."
          
          # Test if sccache can start without failing - use a controlled environment
          if SCCACHE_GHA_ENABLED=true timeout 10s sccache --version >/dev/null 2>&1; then
            echo "✅ sccache connectivity verified, enabling for builds"
            echo "SCCACHE_GHA_ENABLED=true" >> $GITHUB_ENV
            echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV
          else
            echo "⚠️ sccache connectivity failed (GitHub cache service may be down)"
            echo "   Continuing build without sccache to ensure reliability"
            echo "   Build will complete successfully but without sccache optimizations"
            # Explicitly do NOT set RUSTC_WRAPPER so builds use rustc directly
            echo "SCCACHE_DISABLED=true" >> $GITHUB_ENV
          fi
        else
          echo "⚠️ sccache not available, proceeding without sccache"
          echo "SCCACHE_DISABLED=true" >> $GITHUB_ENV
        fi
    
    - name: Run build check
      run: make build