name: CI

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]

env:
  CARGO_TERM_COLOR: always
  # Cache fallback configuration
  # Set DISABLE_CACHE=true to disable all caching (for cache service outages)
  # DISABLE_CACHE: true

jobs:
  test:
    name: Test, Format, and Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [stable]
        include:
          - rust: stable
            check_fmt: true
            check_clippy: true
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust ${{ matrix.rust }}
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.rust }}
        components: ${{ matrix.check_fmt && 'rustfmt' || '' }}${{ matrix.check_clippy && matrix.check_fmt && ',' || '' }}${{ matrix.check_clippy && 'clippy' || '' }}
    
    - name: Install sccache
      uses: mozilla-actions/sccache-action@v0.0.5
      continue-on-error: true
      id: sccache-install
    
    - name: Cache cargo registry and sccache
      uses: actions/cache@v4
      continue-on-error: true
      id: cache-cargo
      with:
        path: |
          ~/.cargo/registry/index
          ~/.cargo/registry/cache
          ~/.cargo/git/db
          target
        key: ${{ runner.os }}-${{ matrix.rust }}-cargo-test-${{ hashFiles('**/Cargo.lock') }}-${{ hashFiles('**/Cargo.toml') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.rust }}-cargo-test-${{ hashFiles('**/Cargo.lock') }}-
          ${{ runner.os }}-${{ matrix.rust }}-cargo-test-${{ hashFiles('**/Cargo.toml') }}-
          ${{ runner.os }}-${{ matrix.rust }}-cargo-test-
          ${{ runner.os }}-${{ matrix.rust }}-cargo-
          ${{ runner.os }}-cargo-
    
    - name: Configure sccache with fallback
      run: |
        # Check if sccache installation and cache are available
        if [ "${{ steps.sccache-install.outcome }}" = "success" ] && [ "${{ env.DISABLE_CACHE }}" != "true" ]; then
          echo "✅ Configuring sccache with GitHub Actions backend"
          echo "SCCACHE_GHA_ENABLED=true" >> $GITHUB_ENV
          echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV
        elif command -v sccache >/dev/null 2>&1 && [ "${{ env.DISABLE_CACHE }}" != "true" ]; then
          echo "⚠️  GitHub Actions cache unavailable, using local sccache"
          echo "SCCACHE_DIR=$HOME/.cache/sccache" >> $GITHUB_ENV
          echo "SCCACHE_CACHE_SIZE=2G" >> $GITHUB_ENV
          echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV
          mkdir -p $HOME/.cache/sccache
        else
          echo "❌ Cache unavailable or disabled, building without cache"
          echo "Cache status: sccache-install=${{ steps.sccache-install.outcome }}, cache-cargo=${{ steps.cache-cargo.outcome }}"
          echo "DISABLE_CACHE=true" >> $GITHUB_ENV
        fi
    
    - name: Check formatting
      if: matrix.check_fmt
      run: cargo fmt -- --check
    
    - name: Run clippy
      if: matrix.check_clippy
      run: make clippy
    
    - name: Run compile check
      run: make compile
    
    - name: Run tests
      run: make test

  build:
    name: Build Verification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
    
    - name: Install sccache
      uses: mozilla-actions/sccache-action@v0.0.5
      continue-on-error: true
      id: sccache-install
    
    - name: Cache cargo registry and sccache
      uses: actions/cache@v4
      continue-on-error: true
      id: cache-cargo
      with:
        path: |
          ~/.cargo/registry/index
          ~/.cargo/registry/cache
          ~/.cargo/git/db
          target
        key: ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}-${{ hashFiles('**/Cargo.toml') }}
        restore-keys: |
          ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}-
          ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.toml') }}-
          ${{ runner.os }}-cargo-build-
          ${{ runner.os }}-stable-cargo-
          ${{ runner.os }}-cargo-
    
    - name: Configure sccache with fallback
      run: |
        # Check if sccache installation and cache are available
        if [ "${{ steps.sccache-install.outcome }}" = "success" ] && [ "${{ env.DISABLE_CACHE }}" != "true" ]; then
          echo "✅ Configuring sccache with GitHub Actions backend"
          echo "SCCACHE_GHA_ENABLED=true" >> $GITHUB_ENV
          echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV
        elif command -v sccache >/dev/null 2>&1 && [ "${{ env.DISABLE_CACHE }}" != "true" ]; then
          echo "⚠️  GitHub Actions cache unavailable, using local sccache"
          echo "SCCACHE_DIR=$HOME/.cache/sccache" >> $GITHUB_ENV
          echo "SCCACHE_CACHE_SIZE=2G" >> $GITHUB_ENV
          echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV
          mkdir -p $HOME/.cache/sccache
        else
          echo "❌ Cache unavailable or disabled, building without cache"
          echo "Cache status: sccache-install=${{ steps.sccache-install.outcome }}, cache-cargo=${{ steps.cache-cargo.outcome }}"
          echo "DISABLE_CACHE=true" >> $GITHUB_ENV
        fi
    
    - name: Run build check
      run: make build